# Generated by Django 4.0.5 on 2022-07-05 20:52

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Coupon',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(choices=[('ELSA50P', 'Lanzamiento'), ('ELSA25P', 'Activaciones 25'), ('ELSA15P', 'Activaciones 15'), ('PXB15ELSA', 'People X Bike'), ('GRG15ELSA', 'Gorigogo'), ('ELSA50WP', 'Whatsapp 50'), ('ELSA25WT', 'Whatsapp 25'), ('ELSA15WG', 'Whatsapp 15'), ('ELSA36020', 'Socios'), ('ELSA25LFS', 'Luis Fer Saldarriaga'), ('ELSALRC25', 'La Ruta Col'), ('ELSAFJP25', 'Fondo Jarlinso'), ('ELSAGRG25', 'Fondo Gorigogo'), ('ELSAFNQ25', 'Fondo Nairo'), ('ELSAEV221', 'Evento 20221'), ('ELSAEV222', 'Evento 20222'), ('ELSAEV223', 'Evento 20223'), ('ELSA3F0001', 'Regalo 0001'), ('ELSA3F0002', 'Regalo 0002'), ('ELSA3F0003', 'Regalo 0003'), ('ELSA3F0004', 'Regalo 0004'), ('ELSA3F0005', 'Regalo 0005'), ('ELSA3F0006', 'Regalo 0006'), ('ELSA3F0007', 'Regalo 0007'), ('ELSA3F0008', 'Regalo 0008'), ('ELSA3F0009', 'Regalo 0009'), ('ELSA3F0010', 'Regalo 0010'), ('ELSA3F0011', 'Regalo 0011'), ('ELSA3F0012', 'Regalo 0012'), ('ELSA3F0013', 'Regalo 0013'), ('ELSA3F0014', 'Regalo 0014'), ('ELSA3F0015', 'Regalo 0015'), ('ELSA3F0016', 'Regalo 0016'), ('ELSA3F0017', 'Regalo 0017'), ('ELSA3F0018', 'Regalo 0018'), ('ELSA3F0019', 'Regalo 0019'), ('ELSA3F0020', 'Regalo 0020'), ('ELSA3F0021', 'Regalo 0021'), ('ELSA3F0022', 'Regalo 0022'), ('ELSA3F0023', 'Regalo 0023'), ('ELSA3F0024', 'Regalo 0024'), ('ELSA3F0025', 'Regalo 0025'), ('ELSA3F0026', 'Regalo 0026'), ('ELSA3F0027', 'Regalo 0027'), ('ELSA3F0028', 'Regalo 0028'), ('ELSA3F0029', 'Regalo 0029'), ('ELSA3F0030', 'Regalo 0030'), ('ELSA3F0031', 'Regalo 0031'), ('ELSA3F0032', 'Regalo 0032'), ('ELSA3F0033', 'Regalo 0033'), ('ELSA3F0034', 'Regalo 0034'), ('ELSA3F0035', 'Regalo 0035'), ('ELSA3F0036', 'Regalo 0036'), ('ELSA3F0037', 'Regalo 0037'), ('ELSA3F0038', 'Regalo 0038'), ('ELSA3F0039', 'Regalo 0039'), ('ELSA3F0040', 'Regalo 0040'), ('ELSA3F0041', 'Regalo 0041'), ('ELSA3F0042', 'Regalo 0042'), ('ELSA3F0043', 'Regalo 0043'), ('ELSA3F0044', 'Regalo 0044'), ('ELSA3F0045', 'Regalo 0045'), ('ELSA3F0046', 'Regalo 0046'), ('ELSA3F0047', 'Regalo 0047'), ('ELSA3F0048', 'Regalo 0048'), ('ELSA3F0049', 'Regalo 0049'), ('ELSA3F0050', 'Regalo 0050'), ('ELSA3F0051', 'Regalo 0051'), ('ELSA3F0052', 'Regalo 0052'), ('ELSA3F0053', 'Regalo 0053'), ('ELSA3F0054', 'Regalo 0054'), ('ELSA3F0055', 'Regalo 0055'), ('ELSA3F0056', 'Regalo 0056'), ('ELSA3F0057', 'Regalo 0057'), ('ELSA3F0058', 'Regalo 0058'), ('ELSA3F0059', 'Regalo 0059'), ('ELSA3F0060', 'Regalo 0060'), ('ELSA3F0061', 'Regalo 0061'), ('ELSA3F0062', 'Regalo 0062'), ('ELSA3F0063', 'Regalo 0063'), ('ELSA3F0064', 'Regalo 0064'), ('ELSA3F0065', 'Regalo 0065'), ('ELSA3F0066', 'Regalo 0066'), ('ELSA3F0067', 'Regalo 0067'), ('ELSA3F0068', 'Regalo 0068'), ('ELSA3F0069', 'Regalo 0069'), ('ELSA3F0070', 'Regalo 0070'), ('ELSA3F0071', 'Regalo 0071'), ('ELSA3F0072', 'Regalo 0072'), ('ELSA3F0073', 'Regalo 0073'), ('ELSA3F0074', 'Regalo 0074'), ('ELSA3F0075', 'Regalo 0075'), ('ELSA3F0076', 'Regalo 0076'), ('ELSA3F0077', 'Regalo 0077'), ('ELSA3F0078', 'Regalo 0078'), ('ELSA3F0079', 'Regalo 0079'), ('ELSA3F0080', 'Regalo 0080')], default='ELSA3F0001', max_length=20, unique=True)),
                ('discount', models.FloatField()),
                ('valid_start_date', models.DateTimeField()),
                ('valid_end_date', models.DateTimeField()),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='CouponToUser',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Membership',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('tier', models.IntegerField(choices=[(3, 'Trimester'), (6, 'Semester'), (12, 'Year')], default=3)),
                ('price', models.DecimalField(decimal_places=4, max_digits=19)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.IntegerField(choices=[(0, 'Pending'), (4, 'Approved'), (6, 'Declined'), (5, 'Expired')], default=0)),
                ('reference_code', models.CharField(max_length=32)),
                ('amount', models.DecimalField(decimal_places=4, max_digits=19)),
                ('currency', models.CharField(choices=[('ARS', 'Argentine Peso'), ('BRL', 'Brazilian Real'), ('CLP', 'Chilean Peso'), ('COP', 'Colombian Peso'), ('MXN', 'Mexican Peso'), ('PEN', 'Peruvian New Sol'), ('USD', 'American Dollar')], default='USD', max_length=3)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
