# Generated by Django 4.0.5 on 2022-07-05 20:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('psychology', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='psychologicalsummary',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='psychologicalquestion',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='psychology.psychologicalquestion'),
        ),
        migrations.AddField(
            model_name='hamiltonsummary',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='hamiltonanxietyquestion',
            name='summary',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='psychology.hamiltonsummary'),
        ),
        migrations.AddField(
            model_name='hamiltonanxietyquestion',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='borghsummary',
            name='answer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='psychology.borgheffortscale'),
        ),
        migrations.AddField(
            model_name='borghsummary',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterUniqueTogether(
            name='hamiltonanxietyquestion',
            unique_together={('number', 'summary')},
        ),
    ]
