# Generated by Django 4.0.5 on 2022-07-06 14:11

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('psychology', '0002_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PsychologicalTraining',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('type', models.CharField(choices=[('RE', 'Respiration'), ('JA', 'Jacobson'), ('SZ', 'Schultz'), ('HA', 'Schwartz & Haynes'), ('VI', 'Visualization')], default='RE', max_length=2)),
                ('title', models.CharField(max_length=55)),
                ('description', models.TextField()),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
