# Generated by Django 4.0.5 on 2022-07-06 16:09

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('psychology', '0004_rename_psychologicaltraining_psychologicaltechnique'),
    ]

    operations = [
        migrations.CreateModel(
            name='HamiltonQuestion',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('number', models.IntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(14)])),
                ('title', models.CharField(max_length=55)),
                ('description', models.TextField()),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='HamiltonQuestionAnswer',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('answer', models.CharField(choices=[('AB', 'Absent'), ('MI', 'Mild'), ('MO', 'Moderate'), ('GR', 'Grave'), ('IN', 'Incapacitating')], default='AB', max_length=2)),
                ('answer_intensity', models.IntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(4)])),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='psychology.hamiltonquestion')),
                ('summary', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='psychology.hamiltonsummary')),
            ],
            options={
                'unique_together': {('question', 'summary')},
            },
        ),
        migrations.CreateModel(
            name='MoodStateProfileSummary',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.RenameModel(
            old_name='MoodStateProfileEntry',
            new_name='MoodStateProfileAnswer',
        ),
        migrations.RemoveField(
            model_name='psycologicalquestionanswer',
            name='is_positive_agreement',
        ),
        migrations.AddField(
            model_name='psycologicalquestionanswer',
            name='agreement_intensity',
            field=models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(6)]),
        ),
        migrations.AlterField(
            model_name='psycologicalquestionanswer',
            name='agreement_answer',
            field=models.CharField(blank=True, choices=[('TD', 'Total disagreement'), ('MD', 'Much disagreement'), ('SD', 'Some disagreement'), ('SA', 'Some agreement'), ('MA', 'Much agreement'), ('TA', 'Total agreement')], default='SA', max_length=2, null=True),
        ),
        migrations.DeleteModel(
            name='HamiltonAnxietyQuestion',
        ),
    ]
