# Generated by Django 4.0.5 on 2022-07-06 20:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('psychology', '0007_remove_hamiltonquestionanswer_answer_intensity_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='MoodProfileAnswer',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('feeling', models.CharField(choices=[('FD', 'Friendly'), ('TE', 'Tense'), ('AN', 'Angry'), ('WR', 'Worn'), ('UH', 'Unhappy'), ('HH', 'Hot headed'), ('DY', 'Dynamic'), ('CF', 'Confused'), ('SR', 'Sorry'), ('TR', 'Trembling'), ('AP', 'Apathetic'), ('FU', 'Furious'), ('CN', 'Considered'), ('SA', 'Sad'), ('AC', 'Active'), ('NR', 'Nervous'), ('GR', 'Grumpy'), ('BL', 'Blue'), ('EN', 'Energetic'), ('PA', 'Panicked'), ('HL', 'Hopeless'), ('RE', 'Relaxed'), ('UW', 'Unworthy'), ('ML', 'Malicious'), ('SP', 'Sympathetic'), ('HT', 'Hard to handle'), ('RT', 'Restless'), ('UC', 'Unable to concentrate'), ('FA', 'Fatigued'), ('US', 'Useful'), ('UP', 'Upset'), ('DC', 'Discouraged'), ('RS', 'Resentful'), ('AL', 'Alone'), ('MS', 'Miserable'), ('CO', 'Confusing'), ('HA', 'Happy'), ('BI', 'Bitter'), ('EX', 'Exhausted'), ('AX', 'Anxious'), ('FR', 'Fight-ready'), ('GM', 'Good mood'), ('SO', 'Somber'), ('DE', 'Desperate'), ('SL', 'Slow'), ('RB', 'Rebellious'), ('DL', 'Defenseless'), ('TI', 'Tired'), ('BW', 'Bewildered'), ('AT', 'Alert'), ('CH', 'Cheated'), ('EF', 'Efficient'), ('TW', 'Trustworthy'), ('BM', 'Bad mood'), ('WL', 'Worthless'), ('FG', 'Forgotten'), ('CA', 'Carefree'), ('TF', 'Terrified'), ('GT', 'Guilty'), ('VG', 'Vigorous'), ('UN', 'Uncertain'), ('DR', 'Drained')], default='FD', max_length=2)),
                ('intensity', models.IntegerField(choices=[(0, 'Never'), (1, 'A little'), (2, 'Moderate'), (3, 'Very much'), (4, 'Alot')], default=2)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.DeleteModel(
            name='MoodStateProfileAnswer',
        ),
        migrations.RenameModel(
            old_name='MoodStateProfileSummary',
            new_name='MoodProfileSummary',
        ),
        migrations.AddField(
            model_name='moodprofileanswer',
            name='summary',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='psychology.moodprofilesummary'),
        ),
    ]
