# Generated by Django 4.0.5 on 2022-07-06 21:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('psychology', '0008_moodprofileanswer_delete_moodstateprofileanswer_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hamiltonquestionanswer',
            name='summary',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='psychology.hamiltonsummary'),
        ),
        migrations.AlterField(
            model_name='moodprofileanswer',
            name='summary',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='psychology.moodprofilesummary'),
        ),
    ]
