# Generated by Django 4.0.5 on 2022-07-07 19:02

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('psychology', '0009_alter_hamiltonquestionanswer_summary_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='IrrationalBeliefAnswer',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('answer', models.CharField(choices=[('TD', 'Total disagreement'), ('MD', 'Much disagreement'), ('SD', 'Some disagreement'), ('SA', 'Some agreement'), ('MA', 'Much agreement'), ('TA', 'Total agreement')], max_length=2)),
                ('intensity', models.IntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(6)])),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='IrrationalBeliefQuestion',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('number', models.IntegerField()),
                ('description', models.CharField(max_length=110)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='IrrationalBeliefQuestionaire',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('day', models.IntegerField(choices=[(1, 'Monday'), (2, 'Tuesday'), (3, 'Wednesday'), (4, 'Thursday'), (5, 'Friday'), (6, 'Saturday'), (7, 'Sunday')], default=1)),
                ('week', models.IntegerField()),
                ('title', models.CharField(max_length=30)),
                ('description', models.TextField()),
                ('summary_description', models.TextField()),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='IrrationalBeliefSummary',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('questionaire', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='psychology.irrationalbeliefquestionaire')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='PsychologicalInventoryAnswer',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('answer', models.IntegerField(choices=[(5, 'Almost always'), (4, 'Many times'), (3, 'Sometimes'), (2, 'A few times'), (1, 'Almost never')], default=3)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='PsychologicalInventoryQuestion',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('number', models.IntegerField()),
                ('description', models.CharField(max_length=110)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='PsychologicalInventoryQuestionaire',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('day', models.IntegerField(choices=[(1, 'Monday'), (2, 'Tuesday'), (3, 'Wednesday'), (4, 'Thursday'), (5, 'Friday'), (6, 'Saturday'), (7, 'Sunday')], default=1)),
                ('week', models.IntegerField()),
                ('title', models.CharField(max_length=52)),
                ('description', models.TextField()),
                ('summary_description', models.TextField()),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='PsychologicalInventorySummary',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('questionaire', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='psychology.psychologicalinventoryquestionaire')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='PsychologicalPlanSummary',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('active', models.BooleanField(default=False)),
                ('start_date', models.DateTimeField()),
                ('end_date', models.DateTimeField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.RemoveField(
            model_name='psycologicalquestionanswer',
            name='agreement_answer',
        ),
        migrations.RemoveField(
            model_name='psycologicalquestionanswer',
            name='agreement_intensity',
        ),
        migrations.RemoveField(
            model_name='psycologicalquestionanswer',
            name='frequency_answer',
        ),
        migrations.RemoveField(
            model_name='psycologicalquestionanswer',
            name='summary',
        ),
        migrations.AlterField(
            model_name='moodprofileanswer',
            name='feeling',
            field=models.CharField(choices=[('FD', 'Friendly'), ('TE', 'Tense'), ('AN', 'Angry'), ('WR', 'Worn'), ('UH', 'Unhappy'), ('HH', 'Hot headed'), ('DY', 'Dynamic'), ('CF', 'Confused'), ('SR', 'Sorry'), ('TR', 'Trembling'), ('AP', 'Apathetic'), ('FU', 'Furious'), ('CN', 'Considered'), ('SA', 'Sad'), ('AC', 'Active'), ('NR', 'Nervous'), ('GR', 'Grumpy'), ('BL', 'Blue'), ('EN', 'Energetic'), ('PA', 'Panicked'), ('HL', 'Hopeless'), ('RE', 'Relaxed'), ('UW', 'Unworthy'), ('ML', 'Malicious'), ('SP', 'Sympathetic'), ('HT', 'Hard to handle'), ('RT', 'Restless'), ('UC', 'Unable to concentrate'), ('FA', 'Fatigued'), ('US', 'Useful'), ('UP', 'Upset'), ('DC', 'Discouraged'), ('RS', 'Resentful'), ('AL', 'Alone'), ('MS', 'Miserable'), ('CO', 'Confusing'), ('HA', 'Happy'), ('BI', 'Bitter'), ('EX', 'Exhausted'), ('AX', 'Anxious'), ('FR', 'Fight-ready'), ('GM', 'Good mood'), ('SO', 'Somber'), ('DE', 'Desperate'), ('SL', 'Slow'), ('RB', 'Rebellious'), ('DL', 'Defenseless'), ('TI', 'Tired'), ('BW', 'Bewildered'), ('AT', 'Alert'), ('CH', 'Cheated'), ('EF', 'Efficient'), ('TW', 'Trustworthy'), ('CR', 'Full of pep'), ('BM', 'Bad mood'), ('WL', 'Worthless'), ('FG', 'Forgetful'), ('CA', 'Carefree'), ('TF', 'Terrified'), ('GT', 'Guilty'), ('VG', 'Vigorous'), ('UN', 'Uncertain'), ('DR', 'Drained')], default='FD', max_length=2),
        ),
        migrations.DeleteModel(
            name='PsychologicalSummary',
        ),
        migrations.AddField(
            model_name='psychologicalinventoryquestion',
            name='questionaire',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='psychology.psychologicalinventoryquestionaire'),
        ),
        migrations.AddField(
            model_name='psychologicalinventoryanswer',
            name='summary',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='psychology.psychologicalinventorysummary'),
        ),
        migrations.AddField(
            model_name='irrationalbeliefquestion',
            name='questionaire',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='psychology.irrationalbeliefquestionaire'),
        ),
        migrations.AddField(
            model_name='irrationalbeliefanswer',
            name='summary',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='psychology.irrationalbeliefsummary'),
        ),
    ]
