# Generated by Django 4.0.5 on 2022-07-07 19:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('psychology', '0010_irrationalbeliefanswer_irrationalbeliefquestion_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='irrationalbeliefquestion',
            name='description',
            field=models.CharField(max_length=140),
        ),
    ]
