# Generated by Django 4.0.5 on 2022-07-07 19:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('psychology', '0011_alter_irrationalbeliefquestion_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='psychologicalinventoryquestion',
            name='description',
            field=models.CharField(max_length=152),
        ),
    ]
