# Generated by Django 4.0.5 on 2022-07-07 19:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('psychology', '0012_alter_psychologicalinventoryquestion_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='psychologicalinventoryanswer',
            name='summary',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='psychology.psychologicalinventorysummary'),
        ),
        migrations.AlterField(
            model_name='psychologicalinventoryquestion',
            name='questionaire',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='psychology.psychologicalinventoryquestionaire'),
        ),
        migrations.AlterField(
            model_name='psychologicalinventorysummary',
            name='questionaire',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='summaries', to='psychology.psychologicalinventoryquestionaire'),
        ),
    ]
