# Generated by Django 4.0.5 on 2022-07-07 19:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('psychology', '0013_alter_psychologicalinventoryanswer_summary_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='irrationalbeliefquestion',
            name='questionaire',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='psychology.irrationalbeliefquestionaire'),
        ),
        migrations.AlterField(
            model_name='irrationalbeliefsummary',
            name='questionaire',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='summaries', to='psychology.irrationalbeliefquestionaire'),
        ),
    ]
