# Generated by Django 4.0.5 on 2022-07-08 15:42

import django.core.validators
from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('psychology', '0014_alter_irrationalbeliefquestion_questionaire_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='IrrationalBeliefScale',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('value', models.CharField(choices=[('TI', 'Totally irrational'), ('VI', 'Very irrational'), ('SI', 'Somewhat irrational'), ('SR', 'Somewhat rational'), ('VR', 'Very rational'), ('TR', 'Totally rational')], default='SR', max_length=2)),
                ('lower_limit', models.IntegerField(validators=[django.core.validators.MinValueValidator(3), django.core.validators.MaxValueValidator(42)])),
                ('upper_limit', models.IntegerField(validators=[django.core.validators.MinValueValidator(3), django.core.validators.MaxValueValidator(42)])),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='irrationalbeliefquestionaire',
            name='summary_scales',
            field=models.ManyToManyField(to='psychology.irrationalbeliefscale'),
        ),
    ]
