# Generated by Django 4.0.5 on 2022-07-08 15:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('psychology', '0015_irrationalbeliefscale_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='irrationalbeliefanswer',
            name='summary',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='psychology.irrationalbeliefsummary'),
        ),
    ]
