# Generated by Django 4.0.5 on 2022-07-11 17:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('psychology', '0016_alter_irrationalbeliefanswer_summary'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='PsycologicalQuestionAnswer',
            new_name='PsychologicalQuestionAnswer',
        ),
    ]
